#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="IvanovWebsite")]
	public partial class DBCoreDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DBCoreDataContext() : 
				base(global::Core.Properties.Settings.Default.IvanovWebsiteConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBCoreDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCoreDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCoreDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBCoreDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tsp_VisitedDestinations")]
		public int tsp_VisitedDestinations([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DestinationID", DbType="Int")] ref System.Nullable<int> destinationID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Caption", DbType="NVarChar(100)")] string caption, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Picture", DbType="NVarChar(200)")] string picture, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShortDesc", DbType="NVarChar(500)")] string shortDesc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lat", DbType="VarChar(20)")] string lat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lng", DbType="VarChar(20)")] string lng, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, destinationID, caption, picture, shortDesc, lat, lng, isPublished);
			destinationID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SaveOffer")]
		public int SaveOffer(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="OfferTypeCode", DbType="Int")] System.Nullable<int> offerTypeCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LocationFromID", DbType="Int")] System.Nullable<int> locationFromID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LocationToID", DbType="Int")] System.Nullable<int> locationToID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartDate", DbType="Date")] System.Nullable<System.DateTime> startDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDate", DbType="Date")] System.Nullable<System.DateTime> endDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartFelxBeforeID", DbType="Int")] System.Nullable<int> startFelxBeforeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StartFelxAfterID", DbType="Int")] System.Nullable<int> startFelxAfterID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndFelxBeforeID", DbType="Int")] System.Nullable<int> endFelxBeforeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndFelxAfterID", DbType="Int")] System.Nullable<int> endFelxAfterID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsOneWay", DbType="Bit")] System.Nullable<bool> isOneWay, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsTwoWay", DbType="Bit")] System.Nullable<bool> isTwoWay, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TravelersCode", DbType="Int")] System.Nullable<int> travelersCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdultCount", DbType="TinyInt")] System.Nullable<byte> adultCount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChildrenCount", DbType="TinyInt")] System.Nullable<byte> childrenCount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StudentCount", DbType="TinyInt")] System.Nullable<byte> studentCount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="InvantCount", DbType="TinyInt")] System.Nullable<byte> invantCount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LuggageCount", DbType="TinyInt")] System.Nullable<byte> luggageCount, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TransportID", DbType="Int")] System.Nullable<int> transportID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StayPlaceID", DbType="Int")] System.Nullable<int> stayPlaceID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromWebsite", DbType="NVarChar(500)")] string fromWebsite, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CarRental", DbType="Bit")] System.Nullable<bool> carRental, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TotalPrice", DbType="Int")] System.Nullable<int> totalPrice, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PricePerPerson", DbType="Int")] System.Nullable<int> pricePerPerson, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CurrencyID", DbType="Int")] System.Nullable<int> currencyID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fname", DbType="NVarChar(20)")] string fname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lname", DbType="NVarChar(20)")] string lname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NationalityID", DbType="Int")] System.Nullable<int> nationalityID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TimeToResearchID", DbType="Int")] System.Nullable<int> timeToResearchID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AddInfo", DbType="NVarChar(MAX)")] string addInfo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReceiveNewsletters", DbType="Bit")] System.Nullable<bool> receiveNewsletters, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReceiveCommercialInfo", DbType="Bit")] System.Nullable<bool> receiveCommercialInfo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AgreeTerms", DbType="Bit")] System.Nullable<bool> agreeTerms)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), offerTypeCode, locationFromID, locationToID, startDate, endDate, startFelxBeforeID, startFelxAfterID, endFelxBeforeID, endFelxAfterID, isOneWay, isTwoWay, travelersCode, adultCount, childrenCount, studentCount, invantCount, luggageCount, transportID, stayPlaceID, fromWebsite, carRental, totalPrice, pricePerPerson, currencyID, fname, lname, email, nationalityID, timeToResearchID, addInfo, receiveNewsletters, receiveCommercialInfo, agreeTerms);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tsp_LastOffers")]
		public int tsp_LastOffers([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OfferID", DbType="Int")] ref System.Nullable<int> offerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Picture", DbType="NVarChar(200)")] string picture, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShortDesc", DbType="NVarChar(500)")] string shortDesc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PdfFile", DbType="NVarChar(200)")] string pdfFile, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, offerID, picture, shortDesc, pdfFile, isPublished);
			offerID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSingleLastOffer", IsComposable=true)]
		public System.Xml.Linq.XElement GetSingleLastOffer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OfferID", DbType="Int")] System.Nullable<int> offerID)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), offerID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_LastOffers", IsComposable=true)]
		public IQueryable<List_LastOffersResult> List_LastOffers([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished)
		{
			return this.CreateMethodCallQuery<List_LastOffersResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), isPublished);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetSingleVisitedDestination", IsComposable=true)]
		public System.Xml.Linq.XElement GetSingleVisitedDestination([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DestinationID", DbType="Int")] System.Nullable<int> destinationID)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), destinationID).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_VisitedDestinations", IsComposable=true)]
		public IQueryable<List_VisitedDestinationsResult> List_VisitedDestinations([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPublished", DbType="Bit")] System.Nullable<bool> isPublished)
		{
			return this.CreateMethodCallQuery<List_VisitedDestinationsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), isPublished);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_Users", IsComposable=true)]
		public IQueryable<List_UsersResult> List_Users()
		{
			return this.CreateMethodCallQuery<List_UsersResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetAuthenticatedUser", IsComposable=true)]
		public System.Xml.Linq.XElement GetAuthenticatedUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(500)")] string password)
		{
			return ((System.Xml.Linq.XElement)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, password).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.tsp_Users")]
		public int tsp_Users([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> iud, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] ref System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoleID", DbType="Int")] System.Nullable<int> roleID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(100)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fname", DbType="NVarChar(20)")] string fname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Lname", DbType="NVarChar(20)")] string lname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iud, userID, roleID, email, password, fname, lname, isActive);
			userID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.List_Dictionaries", IsComposable=true)]
		public IQueryable<List_DictionariesResult> List_Dictionaries([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Level", DbType="Int")] System.Nullable<int> level, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DictionaryCode", DbType="Int")] System.Nullable<int> dictionaryCode, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsVisible", DbType="Bit")] System.Nullable<bool> isVisible)
		{
			return this.CreateMethodCallQuery<List_DictionariesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), level, dictionaryCode, isVisible);
		}
	}
	
	public partial class List_LastOffersResult
	{
		
		private int _OfferID;
		
		private string _Picture;
		
		private string _ShortDesc;
		
		private string _PdfFile;
		
		private bool _IsPublished;
		
		private System.DateTime _CRTime;
		
		public List_LastOffersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfferID", DbType="Int NOT NULL")]
		public int OfferID
		{
			get
			{
				return this._OfferID;
			}
			set
			{
				if ((this._OfferID != value))
				{
					this._OfferID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="NVarChar(200)")]
		public string Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this._Picture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortDesc", DbType="NVarChar(500)")]
		public string ShortDesc
		{
			get
			{
				return this._ShortDesc;
			}
			set
			{
				if ((this._ShortDesc != value))
				{
					this._ShortDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PdfFile", DbType="NVarChar(200)")]
		public string PdfFile
		{
			get
			{
				return this._PdfFile;
			}
			set
			{
				if ((this._PdfFile != value))
				{
					this._PdfFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this._IsPublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
	
	public partial class List_VisitedDestinationsResult
	{
		
		private int _DestinationID;
		
		private string _Caption;
		
		private string _Picture;
		
		private string _ShortDesc;
		
		private string _Lat;
		
		private string _Lng;
		
		private bool _IsPublished;
		
		private System.DateTime _CRTime;
		
		public List_VisitedDestinationsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationID", DbType="Int NOT NULL")]
		public int DestinationID
		{
			get
			{
				return this._DestinationID;
			}
			set
			{
				if ((this._DestinationID != value))
				{
					this._DestinationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(100)")]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="NVarChar(200)")]
		public string Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this._Picture = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortDesc", DbType="NVarChar(500)")]
		public string ShortDesc
		{
			get
			{
				return this._ShortDesc;
			}
			set
			{
				if ((this._ShortDesc != value))
				{
					this._ShortDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lat", DbType="VarChar(20)")]
		public string Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				if ((this._Lat != value))
				{
					this._Lat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lng", DbType="VarChar(20)")]
		public string Lng
		{
			get
			{
				return this._Lng;
			}
			set
			{
				if ((this._Lng != value))
				{
					this._Lng = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPublished", DbType="Bit NOT NULL")]
		public bool IsPublished
		{
			get
			{
				return this._IsPublished;
			}
			set
			{
				if ((this._IsPublished != value))
				{
					this._IsPublished = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
	
	public partial class List_UsersResult
	{
		
		private int _UserID;
		
		private System.Nullable<int> _RoleID;
		
		private string _Email;
		
		private string _Password;
		
		private string _Fname;
		
		private string _Lname;
		
		private bool _IsActive;
		
		private System.DateTime _CRTime;
		
		public List_UsersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleID", DbType="Int")]
		public System.Nullable<int> RoleID
		{
			get
			{
				return this._RoleID;
			}
			set
			{
				if ((this._RoleID != value))
				{
					this._RoleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(100)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fname", DbType="NVarChar(20)")]
		public string Fname
		{
			get
			{
				return this._Fname;
			}
			set
			{
				if ((this._Fname != value))
				{
					this._Fname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lname", DbType="NVarChar(20)")]
		public string Lname
		{
			get
			{
				return this._Lname;
			}
			set
			{
				if ((this._Lname != value))
				{
					this._Lname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRTime", DbType="DateTime NOT NULL")]
		public System.DateTime CRTime
		{
			get
			{
				return this._CRTime;
			}
			set
			{
				if ((this._CRTime != value))
				{
					this._CRTime = value;
				}
			}
		}
	}
	
	public partial class List_DictionariesResult
	{
		
		private int _DictionaryID;
		
		private string _Caption;
		
		private string _Caption1;
		
		private System.Nullable<int> _ParentID;
		
		private string _StringCode;
		
		private System.Nullable<int> _IntCode;
		
		private short _DictionaryCode;
		
		private System.Nullable<bool> _DefVal;
		
		private System.Nullable<bool> _Visible;
		
		private System.Nullable<int> _SortVal;
		
		public List_DictionariesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DictionaryID", DbType="Int NOT NULL")]
		public int DictionaryID
		{
			get
			{
				return this._DictionaryID;
			}
			set
			{
				if ((this._DictionaryID != value))
				{
					this._DictionaryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(200)")]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this._Caption = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption1", DbType="NVarChar(200)")]
		public string Caption1
		{
			get
			{
				return this._Caption1;
			}
			set
			{
				if ((this._Caption1 != value))
				{
					this._Caption1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int")]
		public System.Nullable<int> ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StringCode", DbType="NVarChar(100)")]
		public string StringCode
		{
			get
			{
				return this._StringCode;
			}
			set
			{
				if ((this._StringCode != value))
				{
					this._StringCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntCode", DbType="Int")]
		public System.Nullable<int> IntCode
		{
			get
			{
				return this._IntCode;
			}
			set
			{
				if ((this._IntCode != value))
				{
					this._IntCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DictionaryCode", DbType="SmallInt NOT NULL")]
		public short DictionaryCode
		{
			get
			{
				return this._DictionaryCode;
			}
			set
			{
				if ((this._DictionaryCode != value))
				{
					this._DictionaryCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefVal", DbType="Bit")]
		public System.Nullable<bool> DefVal
		{
			get
			{
				return this._DefVal;
			}
			set
			{
				if ((this._DefVal != value))
				{
					this._DefVal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Visible", DbType="Bit")]
		public System.Nullable<bool> Visible
		{
			get
			{
				return this._Visible;
			}
			set
			{
				if ((this._Visible != value))
				{
					this._Visible = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortVal", DbType="Int")]
		public System.Nullable<int> SortVal
		{
			get
			{
				return this._SortVal;
			}
			set
			{
				if ((this._SortVal != value))
				{
					this._SortVal = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
